name: deploy-certificates
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v4.2.2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Read workflow vars
        run: |
          yarn dlx -q tsx ./scripts/get-workflow-vars.ts --environment ${{ inputs.environment }} >> $GITHUB_ENV
      - name: Configure AWS credentials from ${{ inputs.environment }} account
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/${{ env.APPLICATION_NAME }}-github-actions-deployment-role
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy infrastructure
        run: |
          yarn cdk deploy -c environment=${{ inputs.environment }} --exclusively ${{ env.APPLICATION_NAME }}-${{ inputs.environment }}-certificate-stack --require-approval never
