name: tests
on: [pull_request]
jobs:
  tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v4.1.0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Run tests
        run: |
          docker compose version
          yarn test
